-- ═══════════════════════════════════════════════════════════════════════════════
-- Iron Passport: Database Webhooks for Automatic Cloudflare Pages Rebuild
--
-- When gym or city data changes in Supabase, trigger a Cloudflare Pages
-- deploy hook to rebuild the static site with updated data.
--
-- SETUP:
-- 1. Go to Cloudflare Pages → your project → Settings → Builds & Deployments
-- 2. Under "Deploy Hooks", create a new hook (e.g. "supabase-data-change")
-- 3. Copy the deploy hook URL
-- 4. In Supabase Dashboard: Database → Webhooks → Create webhook
--
-- ═══════════════════════════════════════════════════════════════════════════════

-- Webhook 1: Gyms table changes
-- ─────────────────────────────────────────────────────────────────────────────
-- Name:     rebuild-on-gym-change
-- Table:    gyms
-- Events:   INSERT, UPDATE, DELETE
-- Type:     HTTP Request
-- Method:   POST
-- URL:      <your Cloudflare Pages deploy hook URL>
-- Headers:  Content-Type: application/json

-- Webhook 2: Cities table changes
-- ─────────────────────────────────────────────────────────────────────────────
-- Name:     rebuild-on-city-change
-- Table:    cities
-- Events:   INSERT, UPDATE, DELETE
-- Type:     HTTP Request
-- Method:   POST
-- URL:      <your Cloudflare Pages deploy hook URL>
-- Headers:  Content-Type: application/json

-- ═══════════════════════════════════════════════════════════════════════════════
-- HOW IT WORKS:
-- 1. Admin adds/edits a gym or city via the admin panel
-- 2. Data is saved to Supabase
-- 3. Supabase webhook fires, hitting the Cloudflare deploy hook
-- 4. Cloudflare rebuilds the site (~1-2 minutes)
-- 5. New/updated pages are live
-- ═══════════════════════════════════════════════════════════════════════════════
